#define BTN_HELP                    10
#define BTN_PREV                    11
#define DLG_ID                      1000
#define LBL_WORKGRP                 1001
#define ENT_WORKGRP                 1002
#define LBL_SERVER                  1003
#define ENT_SERVER                  1004
#define LBL_SHARE                   1005
#define ENT_SHARE                   1006
#define LBL_USER                    1007
#define ENT_USER                    1008
#define LBL_PASS                    1009
#define ENT_PASS                    1010
#define LBL_MASTER                  1011
#define ENT_MASTER                  1012
#define CMB_MASTER                  1013
#define LBL_PROP                    1016
#define LBL_EASUPPORT               1021
#define CHK_EASUPPORT               1022
#define ENT_SPASS                   1023
#define GB_LOGIN                    1024
#define GB_PROPERTIES               1026
#define GB_CACHE                     1025
#define GB_BROWSE                   1027
#define LBL_KRB5SUPPORT               1028
#define CHK_KRB5SUPPORT               1029
#define LBL_NTLMv1SUPPORT               1030
#define CHK_NTLMv1SUPPORT               1031
#define LBL_ENCRYPTIONSUPPORT               1032
#define CHK_ENCRYPTIONSUPPORT               1033
#define LBL_CACHETIMEOUT        1014
#define SPIN_CACHETIMEOUT       1015
#define LBL_CACHEDEPTH          1017
#define SPIN_CACHEDEPTH         1018
